// react/src/App.jsx
import './App.css'

function App() {


  return (
    <main>
      <header>
        <section className="flex p-8 gap-6 items-center">
          <aside>
            <h1 className="text-7xl text-center">Earth Echoes</h1>
            <p className="text-lg mt-6">Where nature enthusiasts embark on a digital journey into the wonders of the natural world! Our platform is a sanctuary for those who find solace, inspiration, and excitement in the beauty of our planet. </p>
          </aside>
          <img 
            src='/hero-img.jpg'
            className="w-7/12 max-w-4xl object-cover"
         />
        </section>
        <section  className="text-2xl text-center mt-44 p-4 bg-lime-600 ">
          <p>Discover, Explore, Connect: Unveiling Nature&apos;s Mysteries; Inspiration in Every Sunrise: Embrace the Beauty of the Wild</p>
        </section>
      </header>
    </main>
  )
}

export default App

// vue/src/App.vue
<script setup>

</script>

<template>
   <main>
      <header>
        <section className="flex p-8 gap-6 items-center">
          <aside>
            <h1 className="text-7xl text-center">Earth Echoes</h1>
            <p className="text-lg mt-6">Where nature enthusiasts embark on a digital journey into the wonders of the natural world! Our platform is a sanctuary for those who find solace, inspiration, and excitement in the beauty of our planet. </p>
          </aside>
          <img 
            src='/hero-img.jpg'
            className="w-7/12 max-w-4xl object-cover"
         />
        </section>
        <section  className="text-2xl text-center mt-44 p-4 bg-lime-600 ">
          <p>Discover, Explore, Connect: Unveiling Nature&apos;s Mysteries; Inspiration in Every Sunrise: Embrace the Beauty of the Wild</p>
        </section>
      </header>
    </main>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
